/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'chat-response-handler': EventHandler<never, never>
    'get-chat-response': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'chat-api': ApiRouteHandler<{ message: string; model?: string; temperature?: number }, unknown, { topic: 'chat.process'; data: never }>
    'openai-chat-processor': EventHandler<never, { topic: 'chat.response'; data: never }>
  }
}